language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

# Setup miniconda
before_install:
    # Get Miniconda from Continuum
    # Need to source the script to set the PATH variable in this environment
    # (not the scripts environment)
    - source ci/install-miniconda.sh
    - conda update -q conda
    # Install dependencies
    - conda install python=$TRAVIS_PYTHON_VERSION pip
    - conda install conda-build
    - conda install anaconda-client
    # Show installed pkg information for postmortem diagnostic
    - conda list

# install packages
install:
  - deps='numpy matplotlib scipy pytest'
  - conda create -n apsg $deps python=$TRAVIS_PYTHON_VERSION
  - source activate apsg
  - conda build --python $TRAVIS_PYTHON_VERSION conda-build/apsg
  - conda install apsg --use-local

script:
#  - python -m unittest discover -v
  - python -m pytest -v

after_success:
  - chmod +x ci/deploy_anaconda.sh

deploy:
 # Deploy to Anaconda.org
  - provider: script
    script: ci/deploy_anaconda.sh
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_PYTHON_VERSION = 2.7

notifications:
  email:
    - lexa.ondrej@gmail.com

